[package]
name = "dahl-partition"
version = "0.1.0"
authors = ["David B. Dahl <dahl@stat.byu.edu>"]
edition = "2018"
description = "An efficient representation of a set partition."
license = "MIT OR Apache-2.0"
